### ISSUE TITLE
Trouble controlling CPU in a container

### ISSUE THREAD

**Issue by jschewebbn** [msigwart/fakeload#4]
I'm using fakeload inside a docker container. This container has been limited to 1 CPU at construction time using the nanocpus parameter. The output of `lscpu` in the container shows 4 cpus, but the output of `Runtime.getRuntime().availableProcessors()` is 1. When the load is checked with `OperatingSystemMXBean.getProcessCpuLoad()`, that appears to be using the value of 4 for the number of CPUs rather than the value of 1. Therefore the fake load library keeps requesting more and more CPU.

It seems that the available CPU is reported differently depending on which system call you ask. Ideally `OperatingSystemMXBean` would have a method to get the number of cores so that the load can be computed consistently. However that method doesn't exist. I ended up working around this issue by scaling the load by the number of physical cores reported by the library https://github.com/oshi/oshi.

If you want to support this situation, then I would expect you'd need to pull in the oshi library and do the scaling internally. If not, then the users of the library can take care of this, they just need to know that it's an issue.

**Comment by msigwart** [comment]
Thanks for the issue! I've tried to reproduce the issue, but have not managed to do so. Do you have a docker image (or better the Dockerfile) that I could try out? It would be interesting to know which Java version you use. Also, what docker host do you use?

**Comment by jschewebbn** [comment]
I'm using docker on Ubuntu 18.04 Linux as my host. The Java version is openjdk 11 on Ubuntu 18.04 inside the docker guest. 

I don't have a ready-made Dockerfile that I can share at this point. I'm using the JSON web API to start my containers, so the configuration is in a JSON block. The key is in starting the docker guest with NanoCPUs set to 1000000000 in the HostConfig block on a host with more than 1 CPU core. Here is some example JSON that can be sent to the docker API to create the container.
```
{
  "Image": "/v2/fake_load_server",
  "HostConfig": {
    "NanoCPUs": 1000000000,
    "Memory": 4294967296,
  },
  "ExposedPorts": {}
}
```

**Comment by jschewebbn** [comment]
I've written up a test for you and put it in a repository at https://github.com/jschewebbn/fake-load-bug-4
The readme describes the behavior that I'm seeing and what I expect to see.

**Comment by msigwart** [comment]
Thanks, this is great! Will take a look at it now.

**Comment by msigwart** [comment]
So it turns out that the class `OperatingSystemMXBean` will only be made "container-aware" in Java 14 (see https://bugs.openjdk.java.net/browse/JDK-8228428). 

That is, in Java 14 `OperatingSystemMXBean` offers a new method `getCpuLoad()` that reports the CPU usage of the actual operating environment of the JVM process, whether native OS or virtualized OS, or container etc. 

When the `LoadController` uses this new method instead of `getProcessCpuLoad()`, FakeLoad adjusts the load so that the overall CPU load of the operating environment stays at the desired value even when running in a container.

However, that means that one would have to use Java 14 in order to avoid this bug.

**Comment by jschewebbn** [comment]
Good to know. I've worked around this for now by scaling back the value that I give to `LoadController` based on the container limits.

**Comment by msigwart** [comment]
I updated the library to Java 14 and now use method `getCpuLoad()` in `LoadController`. The fix is available as version 0.5.0 on Maven Central. Thanks again for making me aware of this problem!

**Comment by jschewebbn** [comment]
@msigwart I've been looking into the implementation of these methods in the JVM. Realize that by changing from `getProcessCpuLoad` to `getCpuLoad` you are changing from looking at the CPU load for the JVM process to the CPU load of the whole system. For my use, this is ok. However it may not be what you intend.

**Comment by msigwart** [comment]
Yes, I had thought about it as well. I think for most use cases the CPU load of the system should be fine. If someone requires the CPU load of only the JVM process, they will have to create a new issue :)

Anyway thanks for pointing that out!
