### ISSUE TITLE
Cannot use it on JDK11

### ISSUE THREAD

**Issue by rdehuyss** [msigwart/fakeload#5]
Hi,

I think your code is compiled with JDK14 and thus cannot be used on anything lower than that.

The errormessage I have is: 

com.martensigwart/fakeload/0.5.0/9da30cd4e3754af9e807a322e85fd2070f88597b/fakeload-0.5.0.jar(/com/martensigwart/fakeload/FakeLoads.class)
    class file has wrong version 58.0, should be 55.0

**Comment by msigwart** [comment]
Thanks for the issue. That is correct, version 0.5.0 requires JDK 14 as Java 14 fixed a bug regarding the reporting of CPU consumption in containerized environments ( #4 ).

If you want to use FakeLoad with Java 11 I suggest you use version 0.4.0. Just be aware that CPU simulation might not work correctly if you are running FakeLoad in a container.
