### ISSUE TITLE
Backward compatibility for Java 8 / 11

### ISSUE THREAD

**Issue by Cyb0rk** [msigwart/fakeload#8]
Backward compatibillity for Java 8 / 11 would be great. The only thing to change should be

`operatingSystem.getCpuLoad()`

to 

`operatingSystem.getSystemCpuLoad()`

in LoadController.java

Works fine compiled with JDK 8 and 11. Currently, it is "just" deprecated in Java >= 14.

If not wished by the maintainer: maybe another repo for 8 or 11? Would be lot easier to integrate in projects which have to use the LTS versions of Java.

**Comment by msigwart** [comment]
I agree, backward compatibility would be nice. However, the switch to Java 14 was made to support correct CPU load simulation in containerised environments (#4). 

I would have to test, if `getSystemCpuLoad()` actually provides the same behaviour as `getCpuLoad()` in containers. Not sure yet when I will be able to do so. As an alternative it might actually be easiest to just keep a Java 8/11 compatible version of the library in a different branch or repository.

Will look into as soon as possible, hopefully within the next couple of weeks.

**Comment by msigwart** [comment]
So it took me a bit longer to look into it but FakeLoad (v0.7.0) is now Java 8 backwards compatible (again). Thanks for your patience 😅
